#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
alias vi='vim'
alias vimdiff='vim -d'

# solr
alias solr-start='solr /usr/local/etc/solr/drupal/solr'

# Tmux
alias tmux="TERM=screen-256color-bce tmux"

# Mysql
alias my="mysql -u root -pmeh"

# List all git aliases
alias git_aliases="alias | ag --nocolor '^g.*git'"

# Drush
alias dr='drush'
